server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 15
              burstCapacity: 30
      routes:
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/events
            - Method=GET
          filters:
            - SetPath=/api/event/all
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/events/by-code/{code}
            - Method=GET
          filters:
            - SetPath=/api/event/{code}
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/events
            - Method=POST
          filters:
            - SetPath=/api/event
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/events/{id}
            - Method=PUT
          filters:
            - SetPath=/api/event/{id}
        - id: event-service
          uri: http://${EVENT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/events/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/event/{id}
        - id: ticket-service
          uri: http://${TICKET_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tickets
            - Method=GET
          filters:
            - SetPath=/api/ticket/all
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
        - id: ticket-service
          uri: http://${TICKET_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tickets/by-code/{code}
            - Method=GET
          filters:
            - SetPath=/api/ticket/{code}
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
        - id: ticket-service
          uri: http://${TICKET_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tickets
            - Method=POST
          filters:
            - SetPath=/api/ticket
        - id: ticket-service
          uri: http://${TICKET_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tickets/{id}
            - Method=PUT
          filters:
            - SetPath=/api/ticket/{id}
        - id: ticket-service
          uri: http://${TICKET_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tickets/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/ticket/{id}
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/registrations
            - Method=GET
          filters:
            - SetPath=/api/registration/all
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE, OPTIONS"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Credentials
                value: "true"
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/registrations
            - Method=POST
          filters:
            - SetPath=/api/registration
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:3000"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Content-Type, Authorization"
        
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/registrations/{id}
            - Method=PUT
          filters:
            - SetPath=/api/registration/{id}
        - id: registration-service
          uri: http://${REGISTRATION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/registrations/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/registration/{id}