services:
 mongo-event:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_event_data:/data/db
    
 mysql-registration:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_registration_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-ticket:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_ticket_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 event-service:
  depends_on:
    - mongo-event
  image: florisvanrooy/event-service
  ports:
    - 8080:8080
  links:
    - mongo-event
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-event
   
 ticket-service:
  depends_on:
    - mysql-ticket
  image: florisvanrooy/ticket-service
  ports:
    - 8082:8082
  links:
    - mysql-ticket
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-ticket
   MYSQL_DB_PORT: 3306

 registration-service:
  depends_on:
    - ticket-service
    - event-service
  image: florisvanrooy/registration-service
  ports:
    - 8081:8081
  links:
    - ticket-service
    - event-service
  environment:
   EVENT_SERVICE_BASEURL: http://event-service:8080
   TICKET_SERVICE_BASEURL: http://ticket-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-registration
   MYSQL_DB_PORT: 3306

 api-gateway:
  depends_on:
    - registration-service
    - ticket-service
    - event-service
  image: florisvanrooy/fvr-api-gateway
  ports:
    - 8083:8083
  links:
    - registration-service
    - ticket-service
    - event-service
  environment:
    EVENT_SERVICE_BASEURL: event-service:8080
    REGISTRATION_SERVICE_BASEURL: registration-service:8081
    TICKET_SERVICE_BASEURL: ticket-service:8082

 frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    ports:
      - 3000:80
    depends_on:
      - api-gateway
    environment:
      VITE_API_URL: http://api-gateway:8083

volumes:
 mongodb_event_data:
 mysql_ticket_data:
 mysql_registration_data: