apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-event
  template:
    metadata:
      labels:
        app: mongo-event
    spec:
      containers:
        - name: mongo-event
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-event-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-event-storage
          persistentVolumeClaim:
            claimName: mongodb-event-pvc
